import type { IconProps } from 'nucleo-flags'
import {
  IconAfghanistan,
  IconAlbania,
  IconAlgeria,
  IconAndorra,
  IconAngola,
  IconAntiguaBarbuda,
  IconArgentina,
  IconArmenia,
  IconAustralia,
  IconAustria,
  IconAzerbaijan,
  IconBahamas,
  IconBahrain,
  IconBangladesh,
  IconBarbados,
  IconBelarus,
  IconBelgium,
  IconBelize,
  IconBenin,
  IconBhutan,
  IconBolivia,
  IconBosniaHerzegovina,
  IconBotswana,
  IconBrazil,
  IconBrunei,
  IconBulgaria,
  IconBurkinaFaso,
  IconBurundi,
  IconCambodia,
  IconCameroon,
  IconCanada,
  IconCapeVerde,
  IconCentralAfricanRepublic,
  IconChad,
  IconChile,
  IconChina,
  IconColombia,
  IconComoros,
  IconRepublicCongo,
  IconDemocraticRepublicCongo,
  IconCostaRica,
  IconIvoryCoast,
  IconCroatia,
  IconCuba,
  IconCyprus,
  IconCzechia,
  IconDenmark,
  IconDjibouti,
  IconDominica,
  IconDominicanRepublic,
  IconEastTimor,
  IconEcuador,
  IconEgypt,
  IconElSalvador,
  IconEquatorialGuinea,
  IconEritrea,
  IconEstonia,
  IconEswatini,
  IconEthiopia,
  IconFiji,
  IconFinland,
  IconFrance,
  IconGabon,
  IconGambia,
  IconGeorgia,
  IconGermany,
  IconGhana,
  IconGreece,
  IconGrenada,
  IconGuatemala,
  IconGuinea,
  IconGuineaBissau,
  IconGuyana,
  IconHaiti,
  IconHonduras,
  IconHongKong,
  IconHungary,
  IconIceland,
  IconIndia,
  IconIndonesia,
  IconIran,
  IconIraq,
  IconIreland,
  IconIsrael,
  IconItaly,
  IconJamaica,
  IconJapan,
  IconJordan,
  IconKazakhstan,
  IconKenya,
  IconKiribati,
  IconNorthKorea,
  IconSouthKorea,
  IconKuwait,
  IconKyrgyzstan,
  IconLaos,
  IconLatvia,
  IconLebanon,
  IconLesotho,
  IconLiberia,
  IconLibya,
  IconLiechtenstein,
  IconLithuania,
  IconLuxembourg,
  IconMacau,
  IconMadagascar,
  IconMalawi,
  IconMalaysia,
  IconMaldives,
  IconMali,
  IconMalta,
  IconMarshallIslands,
  IconMauritania,
  IconMauritius,
  IconMexico,
  IconMicronesia,
  IconMoldova,
  IconMonaco,
  IconMongolia,
  IconMontenegro,
  IconMorocco,
  IconMozanbique,
  IconMyanmar,
  IconNamibia,
  IconNauru,
  IconNepal,
  IconNetherlands,
  IconNewZealand,
  IconNicaragua,
  IconNiger,
  IconNigeria,
  IconNorway,
  IconOman,
  IconPakistan,
  IconPalau,
  IconPalestine,
  IconPanama,
  IconPapuaNewGuinea,
  IconParaguay,
  IconPeru,
  IconPhilippines,
  IconPoland,
  IconPortugal,
  IconQatar,
  IconRomania,
  IconRussia,
  IconRwanda,
  IconSaintKittsNevis,
  IconSaintLucia,
  IconSaintVincentGrenadines,
  IconSamoa,
  IconSanMarino,
  IconSaoTomePrincipe,
  IconSaudiArabia,
  IconSenegal,
  IconSerbia,
  IconSeychelles,
  IconSierraLeone,
  IconSingapore,
  IconSlovakia,
  IconSlovenia,
  IconSolomonIslands,
  IconSomalia,
  IconSouthAfrica,
  IconSouthSudan,
  IconSpain,
  IconSriLanka,
  IconSudan,
  IconSuriname,
  IconSweden,
  IconSwitzerland,
  IconSyria,
  IconTaiwan,
  IconTajikistan,
  IconTanzania,
  IconThailand,
  IconTogo,
  IconTonga,
  IconTrinidadTobago,
  IconTunisia,
  IconTurkey,
  IconTurkmenistan,
  IconTuvalu,
  IconUganda,
  IconUkraine,
  IconUnitedArabEmirates,
  IconUnitedKingdom,
  IconUnitedStates,
  IconUruguay,
  IconUzbekistan,
  IconVanuatu,
  IconVaticanCity,
  IconVenezuela,
  IconVietnam,
  IconYemen,
  IconZambia,
  IconZimbabwe,
} from 'nucleo-flags'

import type { ComponentType } from 'react'

import { cn } from '@/lib/cn'

const FLAG_ICONS: Record<string, ComponentType<IconProps>> = {
  AF: IconAfghanistan,
  AL: IconAlbania,
  DZ: IconAlgeria,
  AD: IconAndorra,
  AO: IconAngola,
  AG: IconAntiguaBarbuda,
  AR: IconArgentina,
  AM: IconArmenia,
  AU: IconAustralia,
  AT: IconAustria,
  AZ: IconAzerbaijan,
  BS: IconBahamas,
  BH: IconBahrain,
  BD: IconBangladesh,
  BB: IconBarbados,
  BY: IconBelarus,
  BE: IconBelgium,
  BZ: IconBelize,
  BJ: IconBenin,
  BT: IconBhutan,
  BO: IconBolivia,
  BA: IconBosniaHerzegovina,
  BW: IconBotswana,
  BR: IconBrazil,
  BN: IconBrunei,
  BG: IconBulgaria,
  BF: IconBurkinaFaso,
  BI: IconBurundi,
  KH: IconCambodia,
  CM: IconCameroon,
  CA: IconCanada,
  CV: IconCapeVerde,
  CF: IconCentralAfricanRepublic,
  TD: IconChad,
  CL: IconChile,
  CN: IconChina,
  CO: IconColombia,
  KM: IconComoros,
  CG: IconRepublicCongo,
  CD: IconDemocraticRepublicCongo,
  CR: IconCostaRica,
  CI: IconIvoryCoast,
  HR: IconCroatia,
  CU: IconCuba,
  CY: IconCyprus,
  CZ: IconCzechia,
  DK: IconDenmark,
  DJ: IconDjibouti,
  DM: IconDominica,
  DO: IconDominicanRepublic,
  TL: IconEastTimor,
  EC: IconEcuador,
  EG: IconEgypt,
  SV: IconElSalvador,
  GQ: IconEquatorialGuinea,
  ER: IconEritrea,
  EE: IconEstonia,
  SZ: IconEswatini,
  ET: IconEthiopia,
  FJ: IconFiji,
  FI: IconFinland,
  FR: IconFrance,
  GA: IconGabon,
  GM: IconGambia,
  GE: IconGeorgia,
  DE: IconGermany,
  GH: IconGhana,
  GR: IconGreece,
  GD: IconGrenada,
  GT: IconGuatemala,
  GN: IconGuinea,
  GW: IconGuineaBissau,
  GY: IconGuyana,
  HT: IconHaiti,
  HN: IconHonduras,
  HK: IconHongKong,
  HU: IconHungary,
  IS: IconIceland,
  IN: IconIndia,
  ID: IconIndonesia,
  IR: IconIran,
  IQ: IconIraq,
  IE: IconIreland,
  IL: IconIsrael,
  IT: IconItaly,
  JM: IconJamaica,
  JP: IconJapan,
  JO: IconJordan,
  KZ: IconKazakhstan,
  KE: IconKenya,
  KI: IconKiribati,
  KP: IconNorthKorea,
  KR: IconSouthKorea,
  KW: IconKuwait,
  KG: IconKyrgyzstan,
  LA: IconLaos,
  LV: IconLatvia,
  LB: IconLebanon,
  LS: IconLesotho,
  LR: IconLiberia,
  LY: IconLibya,
  LI: IconLiechtenstein,
  LT: IconLithuania,
  LU: IconLuxembourg,
  MO: IconMacau,
  MG: IconMadagascar,
  MW: IconMalawi,
  MY: IconMalaysia,
  MV: IconMaldives,
  ML: IconMali,
  MT: IconMalta,
  MH: IconMarshallIslands,
  MR: IconMauritania,
  MU: IconMauritius,
  MX: IconMexico,
  FM: IconMicronesia,
  MD: IconMoldova,
  MC: IconMonaco,
  MN: IconMongolia,
  ME: IconMontenegro,
  MA: IconMorocco,
  MZ: IconMozanbique,
  MM: IconMyanmar,
  NA: IconNamibia,
  NR: IconNauru,
  NP: IconNepal,
  NL: IconNetherlands,
  NZ: IconNewZealand,
  NI: IconNicaragua,
  NE: IconNiger,
  NG: IconNigeria,
  NO: IconNorway,
  OM: IconOman,
  PK: IconPakistan,
  PW: IconPalau,
  PS: IconPalestine,
  PA: IconPanama,
  PG: IconPapuaNewGuinea,
  PY: IconParaguay,
  PE: IconPeru,
  PH: IconPhilippines,
  PL: IconPoland,
  PT: IconPortugal,
  QA: IconQatar,
  RO: IconRomania,
  RU: IconRussia,
  RW: IconRwanda,
  KN: IconSaintKittsNevis,
  LC: IconSaintLucia,
  VC: IconSaintVincentGrenadines,
  WS: IconSamoa,
  SM: IconSanMarino,
  ST: IconSaoTomePrincipe,
  SA: IconSaudiArabia,
  SN: IconSenegal,
  RS: IconSerbia,
  SC: IconSeychelles,
  SL: IconSierraLeone,
  SG: IconSingapore,
  SK: IconSlovakia,
  SI: IconSlovenia,
  SB: IconSolomonIslands,
  SO: IconSomalia,
  ZA: IconSouthAfrica,
  SS: IconSouthSudan,
  ES: IconSpain,
  LK: IconSriLanka,
  SD: IconSudan,
  SR: IconSuriname,
  SE: IconSweden,
  CH: IconSwitzerland,
  SY: IconSyria,
  TW: IconTaiwan,
  TJ: IconTajikistan,
  TZ: IconTanzania,
  TH: IconThailand,
  TG: IconTogo,
  TO: IconTonga,
  TT: IconTrinidadTobago,
  TN: IconTunisia,
  TR: IconTurkey,
  TM: IconTurkmenistan,
  TV: IconTuvalu,
  UG: IconUganda,
  UA: IconUkraine,
  AE: IconUnitedArabEmirates,
  GB: IconUnitedKingdom,
  US: IconUnitedStates,
  UY: IconUruguay,
  UZ: IconUzbekistan,
  VU: IconVanuatu,
  VA: IconVaticanCity,
  VE: IconVenezuela,
  VN: IconVietnam,
  YE: IconYemen,
  ZM: IconZambia,
  ZW: IconZimbabwe,
} as const

export type FlagCountryCode = keyof typeof FLAG_ICONS

export function toFlagCountryCode(
  countryCode: string | null | undefined,
): FlagCountryCode | null {
  const normalized = countryCode?.toUpperCase()

  return normalized && normalized in FLAG_ICONS
    ? (normalized as FlagCountryCode)
    : null
}

export function getFlagIcon(countryCode: string | null | undefined) {
  const flag = toFlagCountryCode(countryCode)
  return flag ? FLAG_ICONS[flag] : null
}

export type FlagIconProps = Omit<IconProps, 'children'> & {
  code: string | null | undefined
}

export function FlagIcon({ code, className, ...props }: FlagIconProps) {
  const Icon = getFlagIcon(code)
  if (!Icon) return null

  return (
    <Icon
      aria-hidden={props.title ? undefined : true}
      focusable="false"
      className={cn('shrink-0 select-none', className)}
      {...props}
    />
  )
}
